mystring = input("Введите произвольный текст: ")
print(len(mystring))
mystring = input("Введите произвольный текст: ")
print(mystring.upper())
mystring = input("Введите произвольный текст: ")
print(mystring.lower())
mystring = input("Введите произвольный текст,например Добрый день: ")
print(mystring.replace(' ',''))
mystring = input("Введите произвольный текст,например Добрый день: ")
print(mystring[0])
mystring = input("Введите произвольный текст,например Пока: ")
print(mystring[3])