grades = [[5, 3, 3, 5, 4], [2, 2, 2, 3], [4, 5, 5, 2], [4, 4, 3], [5, 5, 5, 4, 5]]
students = ({'Johnny', 'Bilbo', 'Steve', 'Khendrik', 'Aaron'})
ls = sorted(set(students))
a = sum(grades[0]) / len(grades[0])
b = sum(grades[1]) / len(grades[1])
c = sum(grades[2]) / len(grades[2])
d = sum(grades[3]) / len(grades[3])
e = sum(grades[4]) / len(grades[4])
conclusion = (ls[0],': ' + str(a),ls[1],': ' + str(b),ls[2],': ' + str(c),ls[3],': ' + str(d),ls[4],': ' + str(e))
print(conclusion)
